version: '2'

volumes: 
  dbdata: {}

services:
  nginx:
    image: nginx:1.16.0
    container_name: docker-lemp_nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    networks:
      - dockernet

  php:
    build: ./docker/php/
    container_name: docker-lemp_php
    user: "${UID}:${GID}"
    expose:
      - 9000
    volumes:
      - ./www:/var/www/html:cached
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - dockernet

  mariadb:
    image: mariadb:latest
    container_name: docker-lemp_mariadb
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - dockernet

networks:
  dockernet: 