#!/bin/bash
(
    export DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    mkdir -p $DIR/tmp/.npm
    cd $DIR/tasks

    if [[ $1 == install ]]; then
        exec npm install
        exit 0
    fi

    exec /usr/bin/env node ./index.js $@
)